name: Build docker image

on:
  push:
    branches:
      - main

jobs:
  get-environments:
    runs-on: ubuntu-latest
    steps:
      - name: Get Environments
        id: get-environments
        run: |
          echo 'environments=["yoo"]' >> "$GITHUB_OUTPUT"
    outputs:
      environments: ${{ steps.get-environments.output.environments }}

  testing:
    runs-on: ubuntu-latest
    needs: [get-environments]
    strategy:
      matrix: 
        env:
          - ${{ needs.get-environments.outputs.environments }}
          # env: ${{ fromJson(needs.get-environments.outputs.environments) }} 
        tag:
          - 101
    steps:
      # checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 1
      - name: Run 
        run: |
          echo "env=${{matrix.env}}"
          echo "tag=${{matrix.tag}}"
