name: Build docker image

on:
  workflow_dispatch:
      inputs:
        app-name:
          description: 'Choose helm chart to deploy -OR- ALL for all charts'
          type: choice
          options:
            - talemetry-int-all
            - talemetry-int-api
            - talemetry-int-consumer
            - talemetry-int-flyway
            - talemetry-int-historical-sync-consumer
            - talemetry-int-web
            - talemetry-int-worker

jobs:
  job1:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.app-name == 'talemetry-int-flyway' || github.event.inputs.app-name == 'talemetry-int-all' }}
    steps:
      - name: app-name
        run: |
            echo "[job1] app-name = ${{ github.event.inputs.app-name }}"

  job2:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [job1]
    steps:
      - name: app-name
        run: |
            echo "[job2] app-name = ${{ github.event.inputs.app-name }}"
