name: Build docker image

on:
  push:
    tags:
      - '*'
    branches:
      - main

jobs:
  get-environments:
    runs-on: ubuntu-latest
    steps:
      - name: Get Environments
        id: get-environments
        run: |
          if echo "${{ github.ref_name }}" | grep -Eq '^[0-9]{4}-[0-9]{2}\..*$'; then
            echo "Environment is staging"
            echo 'environments=["staging"]' >> "$GITHUB_OUTPUT"
          elif [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "Environments are [dev, qa]"
            echo 'environments=["dev", "qa"]' >> "$GITHUB_OUTPUT"
          fi
    outputs:
      environments: ${{ steps.get-environments.outputs.environments }}

  testing:
    runs-on: ubuntu-latest
    needs: [get-environments]
    strategy:
      matrix: 
        env: ${{ fromJson(needs.get-environments.outputs.environments) }} 
        tag:
          - 101
    steps:
      # checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 1
      - name: Run 
        run: |
          echo "env=${{matrix.env}}"
          echo "tag=${{matrix.tag}}"
