name: Build docker image

on:
  push:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        env: ${{github.ref_name}}
    steps:
      # checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 1
      - name: Run 
        run: |
          echo "env=${{matrix.env}}"
